name: Build LaTeX PDF

on:
  push:
    paths:
      - 'paper/**'
      - '.github/workflows/latex.yml'

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up TeX Live
        uses: xu-cheng/latex-action@v2
        with:
          root_file: paper/main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: paper-pdf
          path: paper/main.pdf

      - name: Commit PDF to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --rebase
          git add paper/main.pdf
          git commit -m "Auto-compile PDF on push"
          git push
