name: Compile LaTeX and Commit PDF

on:
  push:
    paths:
      - 'paper/**.tex'
      - 'paper/**.bib'
      - '.github/workflows/latex.yml'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ Needed to allow committing back

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: paper/main.tex

    - name: Move compiled PDF to paper folder
      run: |
        mkdir -p paper
        mv main.pdf paper/main.pdf

    - name: Commit and push PDF
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add paper/main.pdf
        git commit -m "Auto-compile LaTeX and update PDF"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

