name: Build and Commit LaTeX PDF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile LaTeX to PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: paper
        latexmk_use_xelatex: true

    - name: Commit and push compiled PDF
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add paper/main.pdf
        git commit -m "🤖 Auto-compile LaTeX PDF and update paper/main.pdf"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
